version: "3.7"
services:
#    redis:
#        image: redis
#        volumes:
#            - ./redis_server/redis.conf:/usr/local/etc/redis/redis.conf
#        ports:
#            - "6379:6379"
    master:
        build:
            context: ./master
            dockerfile: Dockerfile
        image: pic_master_image
        restart: always
        environment:
            - redis_server_ip=redis
        volumes:
          - "./LocalStorage/master:/app/LocalStorage"
        ports:
          - "8082:10050"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: voiss
            MONGO_INITDB_ROOT_PASSWORD: voiss

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: voiss
            ME_CONFIG_MONGODB_ADMINPASSWORD: voiss
            ME_CONFIG_MONGODB_URL: mongodb://voiss:voiss@mongo:27017/

