version: "3.7"
services:
#    redis:
#        image: redis
#        volumes:
#            - ./redis_server/redis.conf:/usr/local/etc/redis/redis.conf
#        ports:
#            - "6379:6379"
    master:
        build:
            context: ./master
            dockerfile: Dockerfile
        image: pic_master_image
        restart: always
        environment:
            - redis_server_ip=redis
        volumes:
          - "./LocalStorage/master:/app/LocalStorage"
        depends_on:
          - redis
        ports:
          - "8082:10050"

#    worker_test:
#        build:
#            context: ./worker_test
#            dockerfile: Dockerfile
#        image: worker_image
#        restart: always
#        environment:
#            - task_name=img_filter
#            - redis_server_ip=redis
#        volumes:
#            - "./LocalStorage/worker:/app/LocalStorage"
#        depends_on:
#            - redis

